<template>
    <div class="form-group">
        <select class="custom-select" v-model="modelData" required @change="$emit('selectOption',modelData)" >
            <option value="">Country</option>
            <option value="United States">US - United States</option>
            <option value="Albania">AL - Albania</option>
            <option value="Algeria">DZ - Algeria</option>
            <option value="American Samoa">AS - American Samoa</option>
            <option value="Andorra">AD - Andorra</option>
            <option value="Angola">AO - Angola</option>
            <option value="Anguilla">AI - Anguilla</option>
            <option value="Antarctica">AQ - Antarctica</option>
            <option value="Antigua And Barbuda">AG - Antigua And Barbuda</option>
            <option value="Argentina">AR - Argentina</option>
            <option value="Armenia">AM - Armenia</option>
            <option value="Aruba">AW - Aruba</option>
            <option value="Australia">AU - Australia</option>
            <option value="Austria">AT - Austria</option>
            <option value="Azerbaijan">AZ - Azerbaijan</option>
            <option value="Bahamas, The">BS - Bahamas, The</option>
            <option value="Bahrain">BH - Bahrain</option>
            <option value="Bangladesh">BD - Bangladesh</option>
            <option value="Barbados">BB - Barbados</option>
            <option value="Belarus">BY - Belarus</option>
            <option value="Belgium">BE - Belgium</option>
            <option value="Belize">BZ - Belize</option>
            <option value="Benin">BJ - Benin</option>
            <option value="Bermuda">BM - Bermuda</option>
            <option value="Bhutan">BT - Bhutan</option>
            <option value="Bolivia">BO - Bolivia</option>
            <option value="Bosnia">BA - Bosnia</option>
            <option value="Botswana">BW - Botswana</option>
            <option value="Bouvet Island">BV - Bouvet Island</option>
            <option value="Brazil">BR - Brazil</option>
            <option value="British Indian Ocean">IO - British Indian Ocean</option>
            <option value="Brunei">BN - Brunei</option>
            <option value="Bulgaria">BG - Bulgaria</option>
            <option value="Burkina Faso">BF - Burkina Faso</option>
            <option value="Burundi">BI - Burundi</option>
            <option value="Cambodia">KH - Cambodia</option>
            <option value="Cameroon">CM - Cameroon</option>
            <option value="Canada">CA - Canada</option>
            <option value="Cape Verde">CV - Cape Verde</option>
            <option value="Cayman Islands">KY - Cayman Islands</option>
            <option value="Central African Republic">CF - Central African Republic</option>
            <option value="Chad">TD - Chad</option>
            <option value="Chile">CL - Chile</option>
            <option value="China">CN - China</option>
            <option value="Christmas Island">CX - Christmas Island</option>
            <option value="Cocos Islands">CC - Cocos Islands</option>
            <option value="Colombia">CO - Colombia</option>
            <option value="Comoros">KM - Comoros</option>
            <option value="Congo">CG - Congo</option>
            <option value="Congo">CD - Congo</option>
            <option value="Cook Islands">CK - Cook Islands</option>
            <option value="Costa Rica">CR - Costa Rica</option>
            <option value="Cote D'Ivoire">CI - Cote D'Ivoire</option>
            <option value="Croatia (Hrvatska)">HR - Croatia (Hrvatska)</option>
            <option value="Cuba">CU - Cuba</option>
            <option value="Cyprus">CY - Cyprus</option>
            <option value="Czech Republic">CZ - Czech Republic</option>
            <option value="Denmark">DK - Denmark</option>
            <option value="Djibouti">DJ - Djibouti</option>
            <option value="Dominica">DM - Dominica</option>
            <option value="Dominican Republic">DO - Dominican Republic</option>
            <option value="East Timor">TP - East Timor</option>
            <option value="Ecuador">EC - Ecuador</option>
            <option value="Egypt">EG - Egypt</option>
            <option value="El Salvador">SV - El Salvador</option>
            <option value="Equatorial Guinea">GQ - Equatorial Guinea</option>
            <option value="Eritrea">ER - Eritrea</option>
            <option value="Estonia">EE - Estonia</option>
            <option value="Ethiopia">ET - Ethiopia</option>
            <option value="Falkland Islands">FK - Falkland Islands</option>
            <option value="Faroe Islands">FO - Faroe Islands</option>
            <option value="Fiji Islands">FJ - Fiji Islands</option>
            <option value="Finland">FI - Finland</option>
            <option value="France">FR - France</option>
            <option value="French Guiana">GF - French Guiana</option>
            <option value="French Polynesia">PF - French Polynesia</option>
            <option value="French Southern">TF - French Southern</option>
            <option value="Gabon">GA - Gabon</option>
            <option value="Gambia, The">GM - Gambia, The</option>
            <option value="Georgia">GE - Georgia</option>
            <option value="Germany">DE - Germany</option>
            <option value="Ghana">GH - Ghana</option>
            <option value="Gibraltar">GI - Gibraltar</option>
            <option value="Greece">GR - Greece</option>
            <option value="Greenland">GL - Greenland</option>
            <option value="Grenada">GD - Grenada</option>
            <option value="Guadeloupe">GP - Guadeloupe</option>
            <option value="Guam">GU - Guam</option>
            <option value="Guatemala">GT - Guatemala</option>
            <option value="Guinea">GN - Guinea</option>
            <option value="Guinea-Bissau">GW - Guinea-Bissau</option>
            <option value="Guyana">GY - Guyana</option>
            <option value="Haiti">HT - Haiti</option>
            <option value="Heard Islands">HM - Heard Islands</option>
            <option value="Honduras">HN - Honduras</option>
            <option value="Hong Kong S.A.R.">HK - Hong Kong S.A.R.</option>
            <option value="Hungary">HU - Hungary</option>
            <option value="Iceland">IS - Iceland</option>
            <option value="India">IN - India</option>
            <option value="Indonesia">ID - Indonesia</option>
            <option value="Iran">IR - Iran</option>
            <option value="Iraq">IQ - Iraq</option>
            <option value="Ireland">IE - Ireland</option>
            <option value="Israel">IL - Israel</option>
            <option value="Italy">IT - Italy</option>
            <option value="Jamaica">JM - Jamaica</option>
            <option value="Japan">JP - Japan</option>
            <option value="Jordan">JO - Jordan</option>
            <option value="Kazakhstan">KZ - Kazakhstan</option>
            <option value="Kenya">KE - Kenya</option>
            <option value="Kiribati">KI - Kiribati</option>
            <option value="Korea">KR - Korea</option>
            <option value="Korea, North">KP - Korea, North</option>
            <option value="Kuwait">KW - Kuwait</option>
            <option value="Kyrgyzstan">KG - Kyrgyzstan</option>
            <option value="Laos">LA - Laos</option>
            <option value="Latvia">LV - Latvia</option>
            <option value="Lebanon">LB - Lebanon</option>
            <option value="Lesotho">LS - Lesotho</option>
            <option value="Liberia">LR - Liberia</option>
            <option value="Libya">LY - Libya</option>
            <option value="Liechtenstein">LI - Liechtenstein</option>
            <option value="Lithuania">LT - Lithuania</option>
            <option value="Luxembourg">LU - Luxembourg</option>
            <option value="Macau S.A.R.">MO - Macau S.A.R.</option>
            <option value="Macedonia">MK - Macedonia</option>
            <option value="Madagascar">MG - Madagascar</option>
            <option value="Malawi">MW - Malawi</option>
            <option value="Malaysia">MY - Malaysia</option>
            <option value="Maldives">MV - Maldives</option>
            <option value="Mali">ML - Mali</option>
            <option value="Malta">MT - Malta</option>
            <option value="Marshall Islands">MH - Marshall Islands</option>
            <option value="Martinique">MQ - Martinique</option>
            <option value="Mauritania">MR - Mauritania</option>
            <option value="Mauritius">MU - Mauritius</option>
            <option value="Mayotte">YT - Mayotte</option>
            <option value="Mexico">MX - Mexico</option>
            <option value="Micronesia">FM - Micronesia</option>
            <option value="Moldova">MD - Moldova</option>
            <option value="Monaco">MC - Monaco</option>
            <option value="Mongolia">MN - Mongolia</option>
            <option value="Montserrat">MS - Montserrat</option>
            <option value="Morocco">MA - Morocco</option>
            <option value="Mozambique">MZ - Mozambique</option>
            <option value="Myanmar">MM - Myanmar</option>
            <option value="Namibia">NA - Namibia</option>
            <option value="Nauru">NR - Nauru</option>
            <option value="Nepal">NP - Nepal</option>
            <option value="Netherlands Antilles">AN - Netherlands Antilles</option>
            <option value="Netherlands, The">NL - Netherlands, The</option>
            <option value="New Caledonia">NC - New Caledonia</option>
            <option value="New Zealand">NZ - New Zealand</option>
            <option value="Nicaragua">NI - Nicaragua</option>
            <option value="Niger">NE - Niger</option>
            <option value="Nigeria">NG - Nigeria</option>
            <option value="Niue">NU - Niue</option>
            <option value="Norfolk Island">NF - Norfolk Island</option>
            <option value="Northern Mariana Islands">MP - Northern Mariana Islands</option>
            <option value="Norway">NO - Norway</option>
            <option value="Oman">OM - Oman</option>
            <option value="Pakistan">PK - Pakistan</option>
            <option value="Palau">PW - Palau</option>
            <option value="Panama">PA - Panama</option>
            <option value="Papua new Guinea">PG - Papua new Guinea</option>
            <option value="Paraguay">PY - Paraguay</option>
            <option value="Peru">PE - Peru</option>
            <option value="Philippines">PH - Philippines</option>
            <option value="Pitcairn Island">PN - Pitcairn Island</option>
            <option value="Poland">PL - Poland</option>
            <option value="Portugal">PT - Portugal</option>
            <option value="Puerto Rico">PR - Puerto Rico</option>
            <option value="Qatar">QA - Qatar</option>
            <option value="Reunion">RE - Reunion</option>
            <option value="Romania">RO - Romania</option>
            <option value="Russia">RU - Russia</option>
            <option value="Rwanda">RW - Rwanda</option>
            <option value="Saint Helena">SH - Saint Helena</option>
            <option value="Saint Kitts And Nevis">KN - Saint Kitts And Nevis</option>
            <option value="Saint Lucia">LC - Saint Lucia</option>
            <option value="Saint Pierre and Miquelon">PM - Saint Pierre and Miquelon</option>
            <option value="Saint Vincent">VC - Saint Vincent</option>
            <option value="Samoa">WS - Samoa</option>
            <option value="San Marino">SM - San Marino</option>
            <option value="Sao Tome and Principe">ST - Sao Tome and Principe</option>
            <option value="Saudi Arabia">SA - Saudi Arabia</option>
            <option value="Senegal">SN - Senegal</option>
            <option value="Seychelles">SC - Seychelles</option>
            <option value="Sierra Leone">SL - Sierra Leone</option>
            <option value="Singapore">SG - Singapore</option>
            <option value="Slovakia">SK - Slovakia</option>
            <option value="Slovenia">SI - Slovenia</option>
            <option value="Solomon Islands">SB - Solomon Islands</option>
            <option value="Somalia">SO - Somalia</option>
            <option value="South Africa">ZA - South Africa</option>
            <option value="South Georgia">GS - South Georgia</option>
            <option value="Spain">ES - Spain</option>
            <option value="Sri Lanka">LK - Sri Lanka</option>
            <option value="Sudan">SD - Sudan</option>
            <option value="Suriname">SR - Suriname</option>
            <option value="Svalbard Island">SJ - Svalbard Island</option>
            <option value="Swaziland">SZ - Swaziland</option>
            <option value="Sweden">SE - Sweden</option>
            <option value="Switzerland">CH - Switzerland</option>
            <option value="Syria">SY - Syria</option>
            <option value="Taiwan">TW - Taiwan</option>
            <option value="Tajikistan">TJ - Tajikistan</option>
            <option value="Tanzania">TZ - Tanzania</option>
            <option value="Thailand">TH - Thailand</option>
            <option value="Togo">TG - Togo</option>
            <option value="Tokelau">TK - Tokelau</option>
            <option value="Tongarn">TO - Tongarn</option>
            <option value="Trinidad And Tobago">TT - Trinidad And Tobago</option>
            <option value="Tunisia">TN - Tunisia</option>
            <option value="Turkey">TR - Turkey</option>
            <option value="Turkmenistan">TM - Turkmenistan</option>
            <option value="Turks And Caicos Islands">TC - Turks And Caicos Islands</option>
            <option value="Tuvalu">TV - Tuvalu</option>
            <option value="Uganda">UG - Uganda</option>
            <option value="Ukraine">UA - Ukraine</option>
            <option value="United Arab Emirates">AE - United Arab Emirates</option>
            <option value="United Kingdom">UK - United Kingdom</option>
            <option value="United States Islands">UM - United States Islands</option>
            <option value="Uruguay">UY - Uruguay</option>
            <option value="Uzbekistan">UZ - Uzbekistan</option>
            <option value="Vanuatu">VU - Vanuatu</option>
            <option value="Vatican City State">VA - Vatican City State</option>
            <option value="Venezuela">VE - Venezuela</option>
            <option value="Vietnam">VN - Vietnam</option>
            <option value="Virgin Islands (British)">VG - Virgin Islands (British)</option>
            <option value="Virgin Islands (US)">VI - Virgin Islands (US)</option>
            <option value="Wallis And Futuna Islands">WF - Wallis And Futuna Islands</option>
            <option value="Yemen">YE - Yemen</option>
            <option value="Yugoslavia">YU - Yugoslavia</option>
            <option value="Zambia">ZM - Zambia</option>
            <option value="Zimbabwe">ZW – Zimbabwe</option>
        </select>
    </div>
</template>
<script>
export default {
    data(){
        return {
            modelData: ''
        }
    }
}
</script>
